### ISSUE TITLE
Does not work on Fedora

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-grub#2]
See https://bugzilla.redhat.com/show_bug.cgi?id=1894407

**Comment by dginhoux** [comment]
Hi, are you sure to have the file located correctly on /etc/default/grub ? and have a symlink at /etc/sysconfig/grub linked to  /etc/default/grub ?

```
root@srv-pxe3:/mnt/gfs_lv_ansible# ll /etc/sysconfig/grub
lrwxrwxrwx 1 root root 15 Aug  8 18:41 /etc/sysconfig/grub -> ../default/grub
root@srv-pxe3:/mnt/gfs_lv_ansible# ll /etc/default/grub
-rw-r--r-- 1 root root 394 Jul  5 20:22 /etc/default/grub
```

**Comment by robertdebock** [comment]
I think /etc/default/grub is the right location:

[Your own GRUB settings are stored in the /etc/default/grub file](Your own GRUB settings are stored in the /etc/default/grub file).

The symlink is not created in this role.

Can you explain more what you are experiencing?

Regards, Robert.

**Comment by dginhoux** [comment]
For me, everything work fine, i use it on RHEL7/8, and debian 10/11.
Maybe @robertdebock you can add a task to ensure this link is created on RHEL family.... i don't know if RH use the /etc/sysconfig/grub instead of /etc/default/grub....  

When this link is here, and grub file configured by thos role, everything is fine.

**Comment by robertdebock** [comment]
Well, thanks all. The bug is closed, CI passes, I guess we're all good here.
